version: '3.7'

services:
  db:
    # MySQL Image used for the database
    image: mysql:8.2.0
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/mysql
      - ./databaseInitScript:/docker-entrypoint-initdb.d:ro
    # Using secrets for sensitive information
    secrets:
      - MYSQL_ROOT_PASSWORD_FILE
    # Environment variables for MySQL configuration
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD_FILE
  
  phpmyadmin:
    # PHP my admin to manage the database
    image: phpmyadmin:5.2.1
    restart: unless-stopped
    # Depends on db to start first
    depends_on:
      - db

  apache:
    # The Apache image is build using the dockerfile
    build: .
    restart: unless-stopped
    # the src folder is mapped to wwww/html on the inside. This will allow apache to see what I edit in ./src
    volumes:
      - ./src:/var/www/html
    # Depends on db to start first
    depends_on:
      - db
    secrets:
      - MYSQL_ROOT_PASSWORD_FILE
    
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '8080:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    
secrets:
  # Secret files containing the MySQL passwords 
  MYSQL_ROOT_PASSWORD_FILE:
      file: ./.secrets/MYSQL_ROOT_PASSWORD_FILE
